version: "3.9"

services:
  book-service:
    build: ./services/book-service
    container_name: book-service
    ports:
      - "8000:8000"
    networks:
      - library-net

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8001:8001"
    networks:
      - library-net

  borrow-service:
    build: ./services/borrow-service
    container_name: borrow-service
    ports:
      - "8002:8002"
    networks:
      - library-net
    depends_on:
      - book-service
      - user-service

  catalog-service:
    build: ./services/catalog-service
    container_name: catalog-service
    ports:
      - "8003:8003"
    networks:
      - library-net
    depends_on:
      - book-service

  frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - "8080:80"
    networks:
      - library-net
    depends_on:
      - book-service
      - borrow-service

networks:
  library-net:
    driver: bridge
