apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow-service
  template:
    metadata:
      labels:
        app: borrow-service
    spec:
      containers:
      - name: borrow-service
        image: borrow-service:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: borrow-service
spec:
  selector:
    app: borrow-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
